### ISSUE TITLE
Display summary of responses before submission

### ISSUE THREAD

**Issue by lacabra** [lacabra/validate-digitalpublicgoods#11]
User could have second thoughts about how s/he responded to one of the questions especially after a second glance at what the user entered earlier prompting the user to want to update their response. If the user is able to see the entire summary of answers provided, then the user can probably revisit and change. So the summary page just allows you to confirm your answers before final submission, similar to job application systems which permits to verify your answers are accurate before final submission.

Cc: @NathanBaleeta

**Comment by lacabra** [comment]
Given the functionality of going back to previous questions introduced in 27d0645a30d568e0e8af62caf0047d97a730cbff, this feature has been deprioritized and will not be implemented for the first release of this tool launching in mid-December. 

However, help would be very much appreciated in opening a pull request (PR) to add this functionality 🙏

**Comment by rachita19082** [comment]
@lacabra I would like to work on this issue if it is available.

**Comment by rachita19082** [comment]
@lacabra Thank you for assigning. 
I would like to clarify some doubts before starting work on this issue. The summary page should appear after all the questions have been answered by the reviewer. It will display all the questions, their responses and confidence levels and provide a link to change their response. And after clicking submit on the page they will be directed to the page which allows them to open a pull request. Is that correct?

**Comment by rachita19082** [comment]
@lacabra I would like to design a sample UI first to demonstrate this functionality and get it reviewed. Would that be the right way to proceed for solving this issue?

**Comment by lacabra** [comment]
> @lacabra Thank you for assigning.
> I would like to clarify some doubts before starting work on this issue. The summary page should appear after all the questions have been answered by the reviewer. It will display all the questions, their responses and confidence levels and provide a link to change their response. And after clicking submit on the page they will be directed to the page which allows them to open a pull request. Is that correct?

Yes, your proposed flow is correct

> @lacabra I would like to design a sample UI first to demonstrate this functionality and get it reviewed. Would that be the right way to proceed for solving this issue?

Yes, this would be great, thank you! 🙏

**Comment by rachita19082** [comment]
@lacabra Please review [this](https://www.figma.com/proto/Sh1MedlDwxmGntobyZklws/UNICEF-Validate-DPG-Summary?node-id=3%3A50&scaling=scale-down&page-id=0%3A1) clickable prototype. It prompts you to click  on "Modify Response" and subsequently modify the answer to demonstrate the workflow I have in mind. I have tried to keep it consistent with the rest of the design principles followed in the application. Please let me know if I missed out on something or if this looks different from what you expect. I have a few questions as well:

- I have only displayed the "Your assessment" part of the question since this is supposed to be a summary. Please let me know if that works. The questions expands on clicking "Modify response" to allow modification.
- I am a little doubtful about the colour of the "Modify Response" button as it matches with the color of "YES" button. Let me know if this works or I should change the colour.

**Comment by rachita19082** [comment]
@lacabra This is designed for a smaller screen size but I believe the placement will remain the same for a desktop view as well, the only change will be in the size of text and buttons.

**Comment by lacabra** [comment]
Thanks @rachita19082 for the clickable prototype, very informative. It looks great. 

I agree with you that the `Modify Response` button should NOT be green. To avoid introducing too many colors, I suggest we keep it blue like the rest of action buttons that are not `Yes` or `No`

Thank you 🙏

**Comment by rachita19082** [comment]
Thank you @lacabra. I'll keep the colour of the button blue. If the design is approved, should I start with the coding part?

**Comment by lacabra** [comment]
@rachita19082: Yes, by all means 💪
