### ISSUE TITLE
Record time to complete a review

### ISSUE THREAD

**Issue by lacabra** [lacabra/validate-digitalpublicgoods#16]
Currently the form records the timestamp at the end of the submission [here](https://github.com/lacabra/validate-digitalpublicgoods/blob/e9b093748842c84b17cbdbafc7ddd2301da36820/components/openpr.js#L193).

In addition to the current timestamping, we would like to record the time difference between the moment that the user starts reviewing the first question to the time they submit, (recorded as a `Time_end - Time_start` in milliseconds) and added as an additional field to the submission. We will later use this additional data point to filter out those submissions where the user quickly browsed the entirety of the form arbitrarily clicking `yes` or `no` without thoughtfully analyzing each question.

**Comment by rachita19082** [comment]
@lacabra I would like to work on this issue. I have gone through the code and I have some idea on how to record the time difference. Can this be assigned to me?

**Comment by lacabra** [comment]
Thank you. Assigned 🙏

**Comment by rachita19082** [comment]
@lacabra Thanks for assigning this to me. In order to tackle this issue, I think we can note the start time [here](https://github.com/lacabra/validate-digitalpublicgoods/blob/e9b093748842c84b17cbdbafc7ddd2301da36820/pages/projects.js#L42) as the reviewing process starts when the user clicks on the project card. Then we can collect the end time [here](https://github.com/lacabra/validate-digitalpublicgoods/blob/e9b093748842c84b17cbdbafc7ddd2301da36820/components/openpr.js#L193) as mentioned in the issue. Then we can record the difference of the end time and start time as an additional field. I am yet to figure out the details of this. Please let me know if my thought process is correct.

**Comment by lacabra** [comment]
Yes, your thought process is correct. You next need to figure out how to store the start timestamp, and make sure you can pass it all the way down to the end, where you'll compute the subtraction.
