### ISSUE TITLE
Submitting PR when validating DPG trying to retrieve reference to 'master' instead of 'main'

### ISSUE THREAD

**Issue by sabinevidal** [lacabra/validate-digitalpublicgoods#29]
Hi @lacabra ! 
I'm an Outreachy applicant and noticed there were a few other applicants having issues when trying to submit their review of a DPG. One of the other applicants noted that this was to do with the process trying to find the `master` branch, which has now been renamed to `main` across the projects.
https://github.com/unicef/publicgoods-candidates/issues/178#issuecomment-940022023 

Have come across a similar issue before, so wanted to check where this could be coming from.

I'm not sure if the production .env file has been updated, but the template still references `master` as the `NEXT_PUBLIC_GITHUB_MAIN` which is used as the `main` const in components/openpr.js https://github.com/lacabra/validate-digitalpublicgoods/blob/main/.env.local.example 
https://github.com/lacabra/validate-digitalpublicgoods/blob/main/components/openpr.js

**Comment by lacabra** [comment]
Thanks @sabinevidal for your investigative work. There was a name mismatch between the env var used in production and the one in the code, plus the fact that the code in `openpr.js` does not include default values was not good. Both have been fixed in the PR linked above, which should fix the errors we have been experiencing. Thanks again 🙏

**Comment by sabinevidal** [comment]
No worries @lacabra ! Always enjoy some investigative work - and it's a great way to familiarise oneself with the codebase and also other contributors' coding practices. Glad I could help 😊
